# Generated by Django 5.2 on 2025-04-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Shahar nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default="Virtual reallik texnologiyalari orqali O'zbekistonning noyob diqqatga sazovor joylarini dunyoga tanitamiz.", verbose_name='Tavsif')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('telegram_url', models.URLField(blank=True, default='#', verbose_name='Telegram havolasi')),
                ('instagram_url', models.URLField(blank=True, default='#', verbose_name='Instagram havolasi')),
                ('facebook_url', models.URLField(blank=True, default='#', verbose_name='Facebook havolasi')),
                ('youtube_url', models.URLField(blank=True, default='#', verbose_name='YouTube havolasi')),
                ('copyright_text', models.CharField(default="© 2025 O'zbekiston VR Sayohatlar. Barcha huquqlar himoyalangan.", max_length=200, verbose_name='Copyright matni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Footer sozlamasi',
                'verbose_name_plural': 'Footer sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(default='header/default_banner.jpg', upload_to='header/', verbose_name='Banner rasmi')),
                ('title', models.CharField(default="O'ZBEKISTONGA XUSH KELIBSIZ", max_length=100, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(default="VR sayohatlar orqali O'zbekistonning go'zal turistik joylariga virtual tashrif buyuring", max_length=200, verbose_name='Pastki sarlavha')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Header sozlamasi',
                'verbose_name_plural': 'Header sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Joy nomi')),
                ('image', models.ImageField(upload_to='attractions/', verbose_name='Rasm')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='tourism_app.city', verbose_name='Shahar')),
            ],
            options={
                'verbose_name': 'Diqqatga Sazovor Joy',
                'verbose_name_plural': ' Diqqatga Sazovor Joylar',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VRVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Video sarlavhasi')),
                ('video_url', models.URLField(verbose_name='YouTube URL')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_videos', to='tourism_app.city')),
            ],
            options={
                'verbose_name': 'VR Video',
                'verbose_name_plural': 'VR Videolar',
                'ordering': ['city', 'title'],
            },
        ),
    ]
