# Generated by Django 5.2 on 2025-04-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0002_vrvideo_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vrvideo',
            options={'verbose_name': 'VR Video', 'verbose_name_plural': 'VR Videolar'},
        ),
        migrations.RemoveField(
            model_name='vrvideo',
            name='description',
        ),
        migrations.AlterField(
            model_name='vrvideo',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tourism_app.city'),
        ),
    ]
